server.port: 8080
server.servlet.contextPath: /service-api-rest/api

spring.jpa.open-in-view: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.show-sql: false
spring.datasource.url:  "jdbc:mysql://127.0.0.1:3306/transactional_credibanco?allowPublicKeyRetrieval=true&useSSL=false"
spring.datasource.password: "Credi1234"
spring.datasource.username: "root"
